apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: log-collector
  namespace: testing
spec:
  selector:
    matchLabels:
      name: nginx
  template:
    metadata:
      labels:
        name: nginx
    spec:
      containers:
      - name: generate-logs
        image: busybox
        args: [/bin/sh, -c, journalctl -b]